name: Tag Deploy Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create (e.g., 0.0.1)'
        required: true

permissions:
  contents: write

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install yarn@1.19.1 -g
          yarn install --ignore-engines

      - name: Build project
        run: |
          yarn build
          sh build.sh

      - name: Push to deploy branch
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/dev-/deploy-/')
          echo "Deploying to branch: $BRANCH_NAME"

          cd dist/
          git init
          git checkout -b $BRANCH_NAME
          git config --local user.email "ningmengchongshui@gmail.com"
          git config --local user.name "ningmengchongshui"
          git config --global core.quotepath false
          git config --global i18n.commitEncoding utf-8
          git config --global i18n.logOutputEncoding utf-8
          git add -A
          git commit -m "workflows - ${{ github.event.head_commit.timestamp }}"
          git remote add github https://yunzaijs:${{ secrets.GH_TOKEN }}@github.com/yunzaijs/genshin.git
          git remote -v
          git push github HEAD:$BRANCH_NAME -f

      - name: Create and push tag
        run: |
          git tag v${{ github.event.inputs.tag }}
          git remote set-url origin https://yunzaijs:${{ secrets.GH_TOKEN }}@github.com/yunzaijs/genshin.git
          git push origin v${{ github.event.inputs.tag }}

      - name: Delete deploy branch
        run: |
          git fetch --all
          git checkout main
          if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
            git branch -d $BRANCH_NAME
            git push origin --delete $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist, skipping deletion."
          fi
