name: Tag Deploy Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Deploy branch to tag (e.g., 0.0.1)'
        required: true
      tag:
        description: 'Tag to create (e.g., 0.0.1)'
        required: true

permissions:
  contents: write

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches and tags
        run: git fetch --all

      - name: Create and push tag
        run: |
          git checkout deploy-${{ github.event.inputs.branch }}
          git tag v${{ github.event.inputs.tag }}
          git remote set-url origin https://yunzaijs:${{ secrets.GH_TOKEN }}@github.com/yunzaijs/genshin.git
          git push origin v${{ github.event.inputs.tag }}

      - name: Delete deploy branch
        run: |
          git checkout main
          git branch -d deploy-${{ github.event.inputs.branch }}
          git push origin --delete deploy-${{ github.event.inputs.branch }}
