name: Auto Build To Deploy

on:
  push:
    branches:
      - dev-* # 匹配以 "dev-" 开头的分支

jobs:
  build-to-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install yarn@1.19.1 -g
          yarn install --ignore-engines

      - name: Build project
        run: |
          yarn build
          sh build.sh
          cp -rf .github dist/.github

      - name: Push to deploy branch
        run: |
          # 获取当前分支名称
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/dev-/deploy-/')
          echo "Deploying to branch: $BRANCH_NAME"

          # 初始化 dist 并推送到 deploy 分支
          cd dist/
          git init
          git checkout -b $BRANCH_NAME # 创建并切换到目标分支
          git config --local user.email "ningmengchongshui@gmail.com"
          git config --local user.name "ningmengchongshui"
          git config --global core.quotepath false
          git config --global i18n.commitEncoding utf-8
          git config --global i18n.logOutputEncoding utf-8
          git add -A
          git commit -m "workflows - ${{ github.event.head_commit.timestamp }}"
          git remote add github https://yunzaijs:${{ secrets.GH_TOKEN }}@github.com/yunzaijs/genshin.git
          git remote -v
          git push github HEAD:$BRANCH_NAME -f
