name: Auto Build To Deploy

on:
  push:
    branches:
      - dev-* # 匹配以 "dev-" 开头的分支

jobs:
  build-to-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install yarn@1.19.1 -g
          yarn install --ignore-engines

      - name: Build project
        run: |
          yarn build
          sh build.sh
          cp -rf .github dist/.github
