name: 版本发布

on:
  workflow_dispatch:
    inputs:
      version:
        description: '要创建的版本 (例如: 0.0.1)'
        required: true
      message:
        description: '用于 deploy 分支的提交信息'
        required: true

permissions:
  contents: write

jobs:
  deploy-version:
    runs-on: ubuntu-latest

    steps:
      - name: 从 dev 分支检出代码库
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: 验证分支名称
        run: |
          echo "Validating branch name: ${{ github.ref_name }}"
          if [[ ! "${{ github.ref_name }}" =~ ^dev- ]]; then
            echo "错误: 当前分支不以“dev-”开头。"
            exit 1
          fi

      - name: 检查 deploy 分支
        run: |
          DEPLOY_BRANCH="deploy"
          git fetch origin $DEPLOY_BRANCH
          if ! git show-ref --verify --quiet refs/remotes/origin/$DEPLOY_BRANCH; then
            echo "错误：远程分支$DEPLOY_branch不存在。请创建它。"
            exit 1
          fi

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 安装依赖
        run: |
          npm install yarn@1.19.1 -g
          yarn install --ignore-engines
          # 检查 node_modules 是否存在
          if [[ ! -d node_modules ]]; then
            echo "错误: node_modules 目录不存在，依赖安装可能失败。"
            exit 1
          fi

      - name: 打包构建
        run: |
          yarn build
          sh build.sh
          # 检查 dist 目录是否存在且不为空
          if [[ ! -d dist || -z $(ls -A dist) ]]; then
            echo "错误: 'dist' 目录不存在或为空，构建步骤可能失败。"
            exit 1
          fi
          # 转移产物
          mv dist ../dist

      - name: 推送产物
        run: |
          DEPLOY_BRANCH="deploy"
          echo "正在推送构建输出到分支: $DEPLOY_BRANCH"

          # 删除依赖
          rm -rf node_modules

          # 放弃更改

          # 切换到分支
          git checkout $DEPLOY_BRANCH

          # 清理非 git 文件夹的其他内容
          find . -mindepth 1 ! -path './.git*' -exec rm -rf {} + || {
            echo "错误: 文件查找并删除出现意外"
          }

          # 二次清理非 git 文件夹的其他内容
          find . -mindepth 1 ! -path './.git*' -exec rm -rf {} + || {
            echo "错误: 文件查找并删除出现意外"
          }

          # 移动 dist 文件夹内容到根目录
          mv ../dist/* ./ || {
            echo "错误: 无法将 'dist' 目录中的文件移动到根目录，目录可能为空。"
            exit 1
          }

          # 开始产出
          git config --local user.email "ningmengchongshui@gmail.com"
          git config --local user.name "ningmengchongshui"
          git config --global push.autoSetupRemote true
          git add -A
          git commit -m "${{github.event.inputs.version}} ${{ github.event.inputs.message }}"
          git push origin $DEPLOY_BRANCH || {
            echo "错误：推送失败，请检查..."
            exit 1
          }
