name: 版本发布

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to create (e.g., 0.0.1)'
        required: true
      message:
        description: 'Commit message for the deploy branch'
        required: true

permissions:
  contents: write

jobs:
  deploy-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository from dev branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Validate branch name
        run: |
          echo "Validating branch name: ${{ github.ref_name }}"
          if [[ ! "${{ github.ref_name }}" =~ ^dev- ]]; then
            echo "Error: Current branch does not start with 'dev-'."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install yarn@1.19.1 -g
          yarn install --ignore-engines

      - name: Build project
        run: |
          yarn build
          sh build.sh
          if [[ ! -d dist ]]; then
            echo "Error: dist directory does not exist. Build step might have failed."
            exit 1
          fi

      - name: Push build output to deploy branch
        run: |
          DEPLOY_BRANCH="deploy"
          echo "Pushing build output to branch: $DEPLOY_BRANCH"

          git fetch origin
          git reset --hard
          git clean -fd

          if ! git show-ref --verify --quiet refs/remotes/origin/$DEPLOY_BRANCH; then
            echo "Remote branch $DEPLOY_BRANCH does not exist. Creating it."
            git checkout --orphan $DEPLOY_BRANCH
            git reset --hard
            git push origin $DEPLOY_BRANCH
          else
            git checkout -B $DEPLOY_BRANCH
          fi

          find . -mindepth 1 ! -name '.git' ! -name 'dist' -exec rm -rf {} +
          mv dist/* ./
          rm -rf dist/

          git config --local user.email "ningmengchongshui@gmail.com"
          git config --local user.name "ningmengchongshui"
          git add -A
          git commit -m "${{github.event.inputs.version}} ${{ github.event.inputs.message }}"
          git push origin $DEPLOY_BRANCH

      - name: Delete dev branch
        run: |
          DEV_BRANCH="${GITHUB_REF##*/}"
          echo "Deleting branch: $DEV_BRANCH"
          if ! git branch -r --merged | grep "origin/${DEV_BRANCH}"; then
            echo "Error: Branch ${DEV_BRANCH} has unmerged changes. Aborting deletion."
            exit 1
          fi
          git push origin --delete $DEV_BRANCH || echo "Branch $DEV_BRANCH already deleted or does not exist."
